name: $[format('1.0.{0}', counter('1.0', 0))]

trigger:
  branches:
    include:
    - main

variables:
- group: bot-plusser

stages:
  - stage: Build
    displayName: 'Build, Run Tests and Publish Artifacts'

    jobs:
    - job: build
      displayName: Build, Run Tests and Publish Artifacts Job
      pool:
        vmImage: windows-latest

      steps:

      - checkout: self
        clean: true

      - task: NuGetToolInstaller@0
        displayName: Use NuGet
        inputs:
          versionSpec: 6.1.0

      - task: DotNetCoreCLI@2
        displayName: Restore NuGet Packages
        inputs:
          command: restore
          projects: '**/*.csproj'

      - task: DotNetCoreCLI@2
        displayName: Build Projects
        inputs:
          projects: '**/*.sln'

      - task: DotNetCoreCLI@2
        displayName: Run Tests
        inputs:
          command: test
          projects: '**/*.*Test*.csproj'

      - task: DotNetCoreCLI@2
        displayName: Publish Web API
        inputs:
          command: publish
          publishWebProjects: false
          projects: '**/$(ProjectPath).csproj'
          arguments: --output $(Build.ArtifactStagingDirectory)

      - task: PublishPipelineArtifact@1
        displayName: Publish Artifact Web API
        inputs:
          targetPath: '$(Build.ArtifactStagingDirectory)'
          artifact: 'WebApp'

  - stage: Deploy
    displayName: 'Deploy Azure App'

    jobs:
    - job: deploy
      displayName: 'Deploy Azure App'
      pool:
        vmImage: windows-latest

      steps:
      
      - task: DownloadPipelineArtifact@2
        displayName: 'Download Web App Files'
        inputs:
          buildType: 'current'
          artifactName: 'WebApp'
          downloadPath: '$(System.ArtifactsDirectory)'

      - task: AzureRmWebAppDeployment@4
        displayName: 'Deploy Azure App Service'
        inputs:
          ConnectionType: 'AzureRM'
          azureSubscription: '$(AzureSubscription)'
          appType: 'webApp'
          WebAppName: '$(AppName)'
          packageForLinux: '$(System.ArtifactsDirectory)/$(ProjectPath).zip'
...
